config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
                      registrations: 'users/registrations',
                      sessions: 'users/sessions',
                      passwords: 'users/passwords',
                      confirmations: 'users/confirmations'
                    }

  resources :topics do
    resources :bookmarks, except: :index
  end
  resources :bookmarks, only: [] do
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :users, only: :show

  get 'home' => 'welcome#index'

  post :incoming, to: 'incoming#create'

  root 'root#root_toggle'

  # For LetterOpenerWeb
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  has_many :likes, dependent: :destroy

  validates :user_id, presence: true
  validates :topic_id, presence: true
  validates :url, length: { minimum: 3 }, presence: true
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!
  respond_to :js

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.build(bookmark_params)
    @bookmark.user_id = current_user.id
    authorize @bookmark
    if @bookmark.save
      flash[:notice] = 'Bookmark saved successfully.'
    else
      flash[:alert] = 'There was an error saving the bookmark. Please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    @bookmark.assign_attributes(bookmark_params)

    if @bookmark.save
      flash[:notice] = 'Bookmark updated successfully.'
    else
      flash[:alert] = 'There was an error saving the bookmark. Please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = 'Bookmark deleted successfully.'
    else
      flash[:alert] = 'There was an error deleting the bookmark. Please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_edit.html.erb
<div class="modal-dialog modal-md">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">X</button>
      <h1>Edit bookmark</h1>
    </div>
    <%= render partial: 'form', locals: {url: topic_bookmark_path(@bookmark.topic, @bookmark)} %>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<div class="form-horizontal">
  <%= form_for(@bookmark, url: url) do |f| %>
  <div class="modal-body">
    <div class="form-group">
      <%= f.label :url, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.url_field :url, class: 'form-control', placeholder: "Enter topic title" %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <div class="form-group col-sm-5 control-label">
      <%= f.submit "OK", class: 'btn btn-default' %>
    </div>
    <div class="form-group col-sm-4 control-label">
      <button class="btn btn-danger" data-dismiss="modal">Cancel</button>
    </div>
  </div>
  <% end %>
</div>

app/views/bookmarks/_new.html.erb
<div class="modal-dialog modal-md">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">X</button>
      <h1>Add new bookmark</h1>
    </div>
    <%= render partial: 'form', locals: {url: topic_bookmarks_path(@topic)} %>
  </div>
</div>

app/views/bookmarks/_show.html.erb
<div class="modal-dialog modal-md">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">X</button>
      <h1><%= @bookmark.url.match(/^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n]+)/im)[1] %></h1>
    </div>
    <div class="form-horizontal">
      <div class="modal-body">
        <div class="form-group">
          <h4 class="col-sm-3 control-label">Url:</h4>
          <div class="col-sm-8">
            <p class='form-control'><%= @bookmark.url %></p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="form-group col-sm-5 control-label">
          <%= link_to "Edit", edit_topic_bookmark_path(@bookmark.topic, @bookmark), class: "btn btn-primary #{edit_disabled}", remote: true %>
        </div>
        <div class="form-group col-sm-4 control-label">
          <%= link_to "Delete", topic_bookmark_path(@bookmark.topic, @bookmark), method: :delete, data: {confirm: 'Are you sure you want to delete this bookmark?'}, class: "btn btn-danger #{edit_disabled}" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/edit.js.erb
$('#modal').html('<%= j render("edit") %>');
$('#modal').modal();

app/views/bookmarks/new.js.erb
$('#modal').html('<%= j render("new") %>');
$('#modal').modal();

app/views/bookmarks/show.js.erb
$('#modal').html('<%= j render("show") %>');
$('#modal').modal();