config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
                      registrations: 'users/registrations',
                      sessions: 'users/sessions',
                      passwords: 'users/passwords',
                      confirmations: 'users/confirmations'
                    }

  resources :topics do
    resources :bookmarks, except: :index
  end
  resources :bookmarks, only: [] do
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :users, only: :show

  get 'home' => 'welcome#index'

  post :incoming, to: 'incoming#create'

  root 'root#root_toggle'

  # For LetterOpenerWeb
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :history

  belongs_to :user
  has_many :bookmarks, dependent: :destroy

  validates :title, length: { minimum: 3 }, presence: true

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_topic, only: :show
  respond_to :js

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.friendly.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @user = current_user
    @topic = @user.topics.build(topic_params)
    if @topic.save
      flash[:notice] = 'Topic was saved successfully.'
      redirect_to @topic
    else
      flash[:alert] = 'Error creating  topic. Please try again.'
      redirect_to topics_path
    end
  end

  def edit
    @topic = Topic.friendly.find(params[:id])
  end

  def update
    @topic = Topic.friendly.find(params[:id])
    @topic.assign_attributes(topic_params)
    if @topic.save
      flash[:notice] = 'Topic was updated successfully.'
    else
      flash[:alert] = 'There was an error saving the topic. Please try again.'
    end
    redirect_to @topic
  end

  def destroy
    @topic = Topic.friendly.find(params[:id])
    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to topics_path
    else
      flash.now[:alert] = 'There was an error deleting the topic. Please try again.'
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end

  def find_topic
    @topic = Topic.friendly.find(params[:id])
    if request.path != topic_path(@topic)
      return redirect_to @topic, status: :moved_permanently
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def disabled
    @topic.bookmarks.empty? ? '' : 'disabled'
  end

  def edit_disabled
    policy(@bookmark).update? ? '' : 'disabled'
  end
end

app/views/topics/_edit.html.erb
<div class="modal-dialog modal-md">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">X</button>
      <h1>Edit topic</h1>
    </div>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/topics/_form.html.erb
<div class="modal-dialog modal-md">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">X</button>
      <h1>Add new topic</h1>
    </div>
    <div class="form-horizontal">
      <%= form_for @topic do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :title, class: 'col-sm-3 control-label' %>
          <div class="col-sm-8">
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="form-group col-sm-5 control-label">
          <%= f.submit "OK", class: 'btn btn-default' %>
        </div>
        <div class="form-group col-sm-4 control-label">
          <button class="btn btn-danger" data-dismiss="modal">Cancel</button>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/_new.html.erb
<%= render partial: 'form' %>

app/views/topics/edit.js.erb
$('#modal').html('<%= j render("new") %>');
$('#modal').modal();

app/views/topics/index.html.erb
<%= link_to new_topic_path, remote: true do %>
  <div class="new text-center">
    <h1>Topics</h1>
    <small>(Click here to add a new topic)</small>
  </div>
<% end %>
<br>
<div class="container">
  <% @topics.each do |topic| %>
    <div class="topic">
      <h3><%= link_to topic.title, topic_path(topic) %></h3>
      <div class="owl-carousel owl-theme">
        <% topic.bookmarks.each do |bookmark| %>
          <div class="bookmark-wrapper">
            <div class="bookmarks">
              <%= link_to topic_bookmark_path(topic, bookmark), remote: true do %>
                <p><%= bookmark.url.match(/^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n]+)/im)[1] %></p>
                <a href="<%= bookmark.url %>" class="urlembed"></a>
              <% end %>
            </div>
            <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
          </div>
        <% end %>
      </div>
      <div class="left-arrow">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </div>
      <div class="right-arrow">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </div>
    </div>
  <% end %>
</div>

app/views/topics/show.html.erb
<%= link_to edit_topic_path, remote: true do %>
  <div class="new text-center">
    <h1><%= @topic.title %></h1>
    <small>(Click here to edit the topic)</small>
    <div class="tooltip-wrapper disabled" data-title="Topic needs to be empty to delete." data-placement="right">
      <%= link_to 'Delete', topic_path, method: :delete, class: "btn btn-md btn-danger #{disabled}", data: {confirm: 'Are you sure you want to delete this post?'} %>
    </div>
  </div>
<% end %>
<div class="container-fluid">
  <% @topic.bookmarks.each do |bookmark| %>
    <div class="child pull-left">
      <div class="bookmarks">
        <%= link_to topic_bookmark_path(@topic, bookmark), remote: true do %>
          <p><%= bookmark.url.match(/^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n]+)/im)[1] %></p>
          <a href="<%= bookmark.url %>" class="urlembed"></a>
        <% end %>
      </div>
      <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
    </div>
  <% end %>
  <%= link_to "Add bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-warning child pull-left', remote: true %>
</div>