config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
                      registrations: 'users/registrations',
                      sessions: 'users/sessions',
                      passwords: 'users/passwords',
                      confirmations: 'users/confirmations'
                    }

  resources :topics do
    resources :bookmarks, except: :index
  end
  resources :bookmarks, only: [] do
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :users, only: :show

  get 'home' => 'welcome#index'

  post :incoming, to: 'incoming#create'

  root 'root#root_toggle'

  # For LetterOpenerWeb
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :uname, use: :history

  has_many :topics, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, length: { minimum: 3, maximum: 100 }, presence: true

  validates :uname,
           presence: true,
           uniqueness: { case_sensitive: false },
           length: { minimum: 3, maximum: 100 }

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
   conditions = warden_conditions.dup
   if login = conditions.delete(:login)
     where(conditions.to_hash).where(["lower(uname) = :value OR lower(email) = :value", { :value => login.downcase }]).first
   elsif conditions.has_key?(:uname) || conditions.has_key?(:email)
     where(conditions.to_hash).first
   end
  end

  def avatar_url(size)
   gravatar_id = Digest::MD5::hexdigest(self.email).downcase
   "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  respond_to :js
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  respond_to :js
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :js
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :js
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_user

  def show
    @user = User.friendly.find(params[:id])
    @user_bookmarks = @user.bookmarks
    @used_topics = []
    @user_bookmarks.each do |bookmark|
      @used_topics << bookmark.topic unless @used_topics.include?(bookmark.topic)
    end


    @liked_bookmarks = @user.likes
    @liked_topics = []
    @liked_bookmarks.each do |like|
      @liked_topics << like.bookmark.topic unless @liked_topics.include?(like.bookmark.topic)
    end
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
    if request.path != user_path(@user)
      return redirect_to @user, status: :moved_permanently
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% if @user == current_user %>
 <h1 class="text-center">My Blocmarks</h1>
<% else %>
  <h1 class="text-center"><%= "#{@user.name}'s Blocmarks" %></h1>
<% end %>
<div class="container">
  <% @used_topics.each do |topic| %>
    <div class="topic">
      <h3><%= link_to topic.title, topic_path(topic) %></h3>
      <div class="owl-carousel owl-theme">
        <% topic.bookmarks.each do |bookmark| %>
          <% if @user_bookmarks.include?(bookmark) %>
            <div class="bookmark-wrapper">
              <div class="bookmarks">
                <%= link_to topic_bookmark_path(topic, bookmark), remote: true do %>
                  <p><%= bookmark.url.match(/^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n]+)/im)[1] %></p>
                  <a href="<%= bookmark.url %>" class="urlembed"></a>
                <% end %>
              </div>
              <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="left-arrow">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </div>
      <div class="right-arrow">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </div>
    </div>
  <% end %>
</div>
<br>
<br>
<h1 class="text-center">Liked Blocmarks</h1>
<br>
<div class="container">
  <% @liked_topics.each do |topic| %>
    <div class="topic">
      <h3><%= link_to topic.title, topic_path(topic) %></h3>
      <div class="owl-carousel owl-theme">
        <% topic.bookmarks.each do |bookmark| %>
          <% if @liked_bookmarks.include?(bookmark.likes.find_by(user_id: @user.id)) %>
            <div class="bookmark-wrapper">
              <div class="bookmarks">
                <%= link_to topic_bookmark_path(topic, bookmark), remote: true do %>
                  <p><%= bookmark.url.match(/^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n]+)/im)[1] %></p>
                  <a href="<%= bookmark.url %>" class="urlembed"></a>
                <% end %>
              </div>
              <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="left-arrow">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </div>
      <div class="right-arrow">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </div>
    </div>
  <% end %>
</div>