config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
                      registrations: 'users/registrations',
                      sessions: 'users/sessions',
                      passwords: 'users/passwords',
                      confirmations: 'users/confirmations'
                    }

  resources :topics do
    resources :bookmarks, except: :index
  end
  resources :bookmarks, only: [] do
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :users, only: :show

  get 'home' => 'welcome#index'

  post :incoming, to: 'incoming#create'

  root 'root#root_toggle'

  # For LetterOpenerWeb
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blocmarks: Share your favorite sites with the world.</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Trade+Winds" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Akronim" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid main">
    <nav>
      <li class="logo">
        <%= link_to 'Blocmarks', root_path %>
      </li>
      <div class="pull-right nav nav-pills">
        <% if Rails.env.development? %>
          <li class="<%= active_class(letter_opener_web_path) %>"><%= link_to 'Mail', letter_opener_web_path, target: :_blank %></li>
        <% end %>
        <% if user_signed_in? %>
          <li class="<%= active_class(user_path(current_user)) %>"><%= link_to "My Blocmarks", user_path(current_user) %></li>
          <li class="<%= active_class(edit_user_registration_path) %>"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="<%= active_class(new_user_registration_path) %>"><%= link_to 'Sign Up', new_user_registration_path, remote: true %></li>
          <li class="<%= active_class(new_user_session_path) %>"><%= link_to 'Sign In', new_user_session_path, remote: true %></li>
        <% end %>
      </div>
    </nav>

    <% if flash[:notice].present? %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert].present? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <div id="modal" class="modal modal-transparent fade"></div>

    <%= yield %>
    
  </body>
</html>